# runtime: python39
# entrypoint: gunicorn -t 600 -b :$PORT main:app

# service: space-utilization
# handlers:
#   # This configures Google App Engine to serve the files in the app's static
#   # directory.
# - url: /static
#   static_dir: static

#   # This handler routes all requests not caught above to your main app. It is
#   # required when static routes are defined, but can be omitted (along with
#   # the entire handlers section) when there are no static files defined.
# - url: /.*
#   script: auto

runtime: python39
service: space-utilization
entrypoint: gunicorn -t 600 -b :$PORT -w 4 main:app
instance_class: F2

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301


# service: default
# runtime: python39
# #instance_class: F4_1G
# entrypoint: gunicorn -w 2 main:app

# handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: main.app
#   secure: always