runtime: python39

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto






















# service: default
# runtime: python39
# #instance_class: F4_1G
# entrypoint: gunicorn -w 2 main:app

# handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: main.app
#   secure: always